services:
#  my-spring-server:
#    build:
#      context : .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    depends_on:
#      ecommercedb-user:
#        condition: service_healthy
#      ecommercedb-product:
#        condition: service_healthy
#      ecommercedb-order:
#        condition: service_healthy
#      my-cache-server:
#        condition: service_healthy

  ecommercedb-user:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_user:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping"]
      interval: 5s
      retries: 10
  ecommercedb-product:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_product:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping"]
      interval: 5s
      retries: 10
  ecommercedb-order:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_order:/var/lib/mysql
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD","mysqladmin","ping" ]
      interval: 5s
      retries: 10

  ecommercedb-payment:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_payment:/var/lib/mysql
    ports:
      - 3309:3306
    healthcheck:
      test: [ "CMD","mysqladmin","ping" ]
      interval: 5s
      retries: 10

  my-cache-server:
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
#    volumes:
#      - ./zookeeper-data:/var/lib/zookeeper
#      - ./zookeeper-logs:/var/log/zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - ./kafka-data:/var/lib/kafka/data
#      - ./kafka-logs:/var/log/kafka