services:
  my-spring-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      my-ecommercedb:
        condition: service_healthy

  my-ecommercedb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : pwd1234
      MYSQL_DATABASE: ecommercedb
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping"]
      interval: 5s
      retries: 10